### PR TITLE
Bump to 3.4.0

### PR DESCRIPTION
**Pull request by krkhan**

### CODE REVIEW

**Comment by anki-code** [comment]
Thanks @krkhan !

**Comment by Wicloz** [comment]
Could you please attach the build result to the release too? Those are very helpful.

**Comment by anki-code** [comment]
@Wicloz done - https://github.com/xxh/fish-portable/releases/tag/3.4.0

**Comment by Wicloz** [comment]
I can confirm that it works, many thanks!

**Pull request merged**
